import { z } from "zod";
import type { ControlSpec } from "../layer2/createControlPanel.js";
import { createSystemContainer, finalize, runBuild } from "../layer2/orchestration.js";
import type { ToolContext, ToolRegistrar } from "../types.js";

const q = (value: string): string => JSON.stringify(value);

/**
 * Procedural asemic-writing generator. A Script SOP lays out `rows` baselines of `glyphs`
 * per row; each glyph is a short chain of `strokes` connected segments whose control points
 * walk a noise-perturbed pen — random but writing-like (left-to-right baseline flow, small
 * ascenders/descenders, occasional pen-lifts between glyphs). The resulting polylines are
 * thickened into tubes and rendered with an orthographic camera as calligraphic line art.
 *
 * Genuinely new: no existing tool draws asemic glyph strokes. Complements create_growth_system
 * (L-system branches) and create_vector_lines (image-traced contours) as the "generated
 * strokes from nothing" idiom.
 */

const rgb = z.coerce.number().min(0).max(1);

export const createAsemicWritingSchema = z.object({
  rows: z.coerce
    .number()
    .int()
    .min(1)
    .max(40)
    .default(8)
    .describe("Number of baselines (lines of writing) stacked top to bottom."),
  glyphs: z.coerce
    .number()
    .int()
    .min(1)
    .max(64)
    .default(14)
    .describe("Glyphs per row, laid left to right along the baseline."),
  strokes: z.coerce
    .number()
    .int()
    .min(2)
    .max(12)
    .default(5)
    .describe("Control points per glyph — more strokes = more elaborate, script-like marks."),
  jitter: z.coerce
    .number()
    .min(0)
    .max(1)
    .default(0.55)
    .describe(
      "How far the pen wanders vertically per stroke (fraction of the line height). 0 = flat dashes, 1 = wild scrawl.",
    ),
  slant: z.coerce
    .number()
    .min(-0.6)
    .max(0.6)
    .default(0.12)
    .describe("Italic slant applied to every glyph (x-shear per unit height). 0 = upright."),
  lift_chance: z.coerce
    .number()
    .min(0)
    .max(1)
    .default(0.25)
    .describe(
      "Probability the pen lifts (breaks the polyline) between adjacent strokes, giving disconnected marks.",
    ),
  thickness: z.coerce
    .number()
    .positive()
    .default(0.004)
    .describe("Tube SOP radius for the rendered ink strokes."),
  ink_color: z
    .tuple([rgb, rgb, rgb])
    .default([0.9, 0.9, 0.92])
    .describe("Stroke (ink) colour (RGB 0..1)."),
  background: z
    .tuple([rgb, rgb, rgb])
    .default([0.06, 0.05, 0.07])
    .describe("Page / background colour (RGB 0..1)."),
  seed: z.coerce
    .number()
    .int()
    .default(1)
    .describe("RNG seed — same seed reproduces the same page of writing."),
  parent_path: z
    .string()
    .default("/project1")
    .describe(
      "Parent network where the asemic-writing container is created (default '/project1').",
    ),
});
type CreateAsemicWritingArgs = z.infer<typeof createAsemicWritingSchema>;

/**
 * Script SOP cook callback. Reads its config JSON from the docked `cfg` DAT, then walks a
 * pen across `rows × glyphs` cells emitting one polyline per unbroken run of strokes.
 * Live-overrides Jitter/Slant/Seed from the parent COMP's custom pars if present so the
 * exposed controls actually redraw the page.
 */
const ASEMIC_CALLBACK = `# Auto-generated by create_asemic_writing.
import json, math, random

def cook(scriptOp):
    scriptOp.clear()
    try:
        cfg = json.loads(op('cfg').text)
    except Exception:
        return
    try:
        p = parent()
        for json_key, par_name in (('jitter', 'Jitter'), ('slant', 'Slant'), ('seed', 'Seed')):
            par = getattr(p.par, par_name, None)
            if par is not None:
                cfg[json_key] = par.eval()
    except Exception:
        pass

    rows = int(cfg.get('rows', 8))
    glyphs = int(cfg.get('glyphs', 14))
    strokes = int(cfg.get('strokes', 5))
    jitter = float(cfg.get('jitter', 0.55))
    slant = float(cfg.get('slant', 0.12))
    lift_chance = float(cfg.get('lift_chance', 0.25))
    rng = random.Random(int(cfg.get('seed', 1)))

    # Page spans -1..1 in x and y; leave a small margin.
    margin = 0.08
    x0, x1 = -1.0 + margin, 1.0 - margin
    y0, y1 = 1.0 - margin, -1.0 + margin
    line_h = (y0 - y1) / max(rows, 1)
    glyph_w = (x1 - x0) / max(glyphs, 1)
    amp = jitter * line_h * 0.4

    def flush(cp):
        if len(cp) >= 2:
            try:
                poly = scriptOp.appendPoly(len(cp), closed=False, addPoints=True)
                for i, pt in enumerate(cp):
                    poly[i].point.x = pt[0]
                    poly[i].point.y = pt[1]
                    poly[i].point.z = 0.0
            except Exception:
                pass

    for r in range(rows):
        baseline = y0 - (r + 0.6) * line_h
        for g in range(glyphs):
            gx0 = x0 + g * glyph_w
            cur = []
            for s in range(strokes):
                t = s / max(strokes - 1, 1)
                # advance the pen left->right across the glyph cell
                x = gx0 + t * glyph_w * 0.82
                # vertical wander around the baseline, biased upright with small asc/desc
                y = baseline + (rng.random() - 0.5) * 2.0 * amp
                # apply italic slant relative to the baseline
                x += (y - baseline) * slant
                cur.append((x, y))
                # occasional pen-lift breaks the stroke into disconnected marks
                if s < strokes - 1 and rng.random() < lift_chance:
                    flush(cur)
                    cur = []
            flush(cur)
    return
`;

export async function createAsemicWritingImpl(ctx: ToolContext, args: CreateAsemicWritingArgs) {
  return runBuild(async () => {
    const builder = await createSystemContainer(ctx, args.parent_path, "asemic_writing");
    const [ir, ig, ib] = args.ink_color;
    const [bgr, bgg, bgb] = args.background;

    // Config DAT — the Script SOP reads this each cook to draw the page.
    const cfgDat = await builder.add("textDAT", "cfg");
    const cfgPayload = {
      rows: args.rows,
      glyphs: args.glyphs,
      strokes: args.strokes,
      jitter: args.jitter,
      slant: args.slant,
      lift_chance: args.lift_chance,
      seed: args.seed,
    };
    await builder.python(`op(${q(cfgDat)}).text = ${q(JSON.stringify(cfgPayload, null, 2))}`);

    // Script SOP + docked callback DAT.
    const write = await builder.add("scriptSOP", "write");
    const writeCb = await builder.add("textDAT", "write_cb");
    await builder.python(
      `_cb = op(${q(writeCb)})\n_cb.text = ${q(ASEMIC_CALLBACK)}\n_s = op(${q(write)})\n_s.par.callbacks = _cb.name`,
    );

    // Thicken polylines into tubes so the ink strokes have body under the ortho camera.
    const thicken = await builder.add("tubeSOP", "ink", {
      rad1: args.thickness,
      rad2: args.thickness,
      cols: 3,
    });
    await builder.connect(write, thicken);

    // Geometry COMP (builder clears its default torus) renders the ink. A cross-container
    // Select SOP pulls the tubed strokes in and is render-flagged.
    const geo = await builder.add("geometryCOMP", "geo");
    const renderIn = await builder.add("selectSOP", "in1", { sop: thicken }, geo);
    await builder.python(`_n = op(${q(renderIn)})\n_n.render = True\n_n.display = True`);

    const mat = await builder.add("constantMAT", "mat", { colorr: ir, colorg: ig, colorb: ib });
    await builder.setParams(geo, { material: mat });

    // Orthographic camera looking straight at the page so the writing reads as flat 2D.
    const cam = await builder.add("cameraCOMP", "cam", {
      tz: 2.4,
      projection: "ortho",
      orthowidth: 2.2,
    });
    const light = await builder.add("lightCOMP", "light", { tz: 4 });
    const render = await builder.add("renderTOP", "render", {
      camera: cam,
      geometry: geo,
      lights: light,
      bgcolorr: bgr,
      bgcolorg: bgg,
      bgcolorb: bgb,
      bgcolora: 1,
    });
    const out = await builder.add("nullTOP", "out1");
    await builder.connect(render, out);

    builder.warnings.push(
      "The Script SOP re-draws the page each cook (parameter change re-seeds from Seed), so it is stable under a paused timeline. Glyphs are noise-perturbed strokes, not any real script — output is asemic (meaning-free) by design.",
    );

    const controls: ControlSpec[] = [
      { name: "Jitter", type: "float", min: 0, max: 1, default: args.jitter },
      { name: "Slant", type: "float", min: -0.6, max: 0.6, default: args.slant },
      {
        name: "Thickness",
        type: "float",
        min: 0.001,
        max: 0.03,
        default: args.thickness,
        bind_to: [`${thicken}.rad1`, `${thicken}.rad2`],
      },
      { name: "Seed", type: "int", min: 0, max: 9999, default: args.seed },
    ];

    return finalize(ctx, {
      summary: `Built an asemic-writing page (${args.rows} rows × ${args.glyphs} glyphs, ${args.strokes} strokes each, jitter ${args.jitter}, slant ${args.slant}) rendered to ${out} — Script SOP pen strokes → Tube SOP → ortho Render TOP.`,
      builder,
      outputPath: out,
      capturePreviewImage: true,
      controls,
      extra: {
        rows: args.rows,
        glyphs: args.glyphs,
        strokes: args.strokes,
        jitter: args.jitter,
        slant: args.slant,
        lift_chance: args.lift_chance,
        thickness: args.thickness,
        seed: args.seed,
        cfg_dat: cfgDat,
        write_sop: write,
        output_path: out,
      },
    });
  });
}

export const registerCreateAsemicWriting: ToolRegistrar = (server, ctx) => {
  server.registerTool(
    "create_asemic_writing",
    {
      title: "Create asemic writing",
      description:
        "Generate a page of procedural asemic writing — random-but-writing-like glyph strokes that flow left-to-right along stacked baselines but spell nothing. A Script SOP lays out `rows` × `glyphs` cells; each glyph is a short chain of `strokes` control points walking a noise-perturbed pen, with italic `slant`, per-stroke `jitter`, and occasional pen-lifts (`lift_chance`) that break marks apart. The polylines are thickened into tube ink strokes and rendered with an orthographic camera as calligraphic line art on a coloured page. Deterministic per `seed`. Genuinely distinct from create_growth_system (L-system branches) and create_vector_lines (image-traced contours). Creates a new baseCOMP under `parent_path`. Exposes Jitter, Slant, Thickness, and Seed controls. Returns a summary plus a JSON block with the container path, created node paths, output path, exposed controls, node errors, warnings, and an inline preview image.",
      inputSchema: createAsemicWritingSchema.shape,
      annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
    },
    (args) => createAsemicWritingImpl(ctx, args),
  );
};
